swagger: '2.0'
info:
  title: view-counter-api counts-website-viewers
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://backend-272833152577.us-central1.run.app
paths:
  /assets/{asset}:
    get:
      parameters:
        - in: path
          name: asset
          type: string
          required: true
          description: Name of the asset.
      summary: Assets
      operationId: getAsset
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /:
    get:
      summary: Root hello world endpoint
      operationId: hello
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /visitor-count:
    get:
      summary: Get current visitor count
      operationId: getVisitorCount
      responses:
        '200':
          description: Visitor count response
          schema:
            type: object
            properties:
              count:
                type: integer
    post:
      summary: Increment visitor count
      operationId: incrementVisitorCount
      responses:
        '200':
          description: Updated visitor count response
          schema:
            type: object
            properties:
              count:
                type: integer
        '500':
          description: Error incrementing count
          schema:
            type: object
            properties:
              error:
                type: string
