project_id  = "portfolio-website-464012"
region      = "us-central1"
bucket_name = "resume-site-2"  
domain_name = "www.aangiras.com" 
uptime_check_name = "backend-healthcheck"
uptime_check_url = "https://backend-272833152577.us-central1.run.app"
notification_email = "shraddhaaangiras0911@gmail.com"