name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve
      env:
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: "us-central1"
        TF_VAR_bucket_name: "resume-site-2"
        TF_VAR_domain_name: "www.aangiras.com"
      working-directory: ./iac


    - name: Sync files to GCS
      run: |
        gsutil -m rsync -r -x "node_modules(/.*)?" ./site gs://${{ secrets.GCP_BUCKET_NAME }}
      working-directory: ./
