name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP (Frontend)
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Sync frontend to GCS
      run: |
        gsutil -m rsync -r -x "node_modules(/.*)?" ./site gs://${{ secrets.GCP_BUCKET_NAME }}

    - name: Invalidate Cloud CDN Cache
      run: |
        gcloud compute url-maps invalidate-cdn-cache static-url-map \
          --path "/*" \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --quiet
